---
title: "Final Project"
output:
  html_document:
    toc: yes
    toc_float: yes
---

## Deadline 1: Proposals (2/8)

The first component of the project is a proposal. This is a written document that can be done in markdown, Word, etc. Your proposal is due by Wednesday, 2/8.

### Content

Your final proposals should contain the following content:

* **Group Members:** List the members of your group
* **Title:** Your title
* **Purpose:** Describe the general topic/phenomenon you want to study, as well some focused
questions that you hope to answer and specific hypotheses that you intend to assess.
*  **Data**: Describe the data that you plan to use, with specifications of where it can be found (URL) and a short description. Eventually, you will probably want to combine data from multiple sources into one file. We will discuss data management techniques in the coming weeks, but for now you should simply list multiple sources if you have them.
* **Population:** Specify what the observational units are (i.e. the rows of the data frame), describe the larger population/phenomenon to which you'll try to generalize, and (if appropriate) estimate roughly how many such individuals there are in the population.
* **Response Variable:** What is the response variable? What are its units? Estimate the range of possible values that it may take on.
* **Explanatory Variables:** Describe the variables that you'll examine for each observational unit (i.e. the columns of the data frame). Carefully define each variable and describe how each was measured. For categorical variables, list the possible categories; for quantitative variables, specify the units of measurement. You may want to add more variables later on, but you should have at least 5 variables already.


### Places to Find Data


Public data sets are available from hundreds of different websites, on virtually any topic. You might not be able to find the exact data that you want, but you should be able to find data that is relevant to your topic. You may also want to refine your research question so that it can be more clearly addressed by the data that you found. But be creative! Go find the data that you want!

Below is a list of places to get started, but this list should be considered grossly non-exhaustive:


* Finding Data on the Internet (http://blog.revolutionanalytics.com/2011/10/where-to-look-for-data.html) 
* Gapminder ([www.gapminder.org](https://www.gapminder.org/))
* Data.gov ([explore.data.gov](https://catalog.data.gov/dataset))
* Awesome public data sets on GitHub (https://github.com/aloy/awesome-public-datasets)
* U.S. Bureau of Labor Statistics ([www.bls.gov](https://www.bls.gov/))
* U.S. Census Bureau ([www.census.gov](http://www.census.gov/))


Keep the following in mind as you select your topic and data set:

* You need to have enough data to draw meaningful inferences. There is no magic number of individuals required for all projects, but aim for at least 200 observations (or about 12 observations per predictor at a minimum) and make sure there are at least 20 observations in each category of each of your categorical variables (if you have any).
* An interesting data set will be a mix of continuous and categorical variables.
* When you're looking at a data set, ask yourself, is this a sample from some greater population or is this the population itself? Many of the inferential techniques that we've used are most appropriate for use on sampled data.



## Deadline 2: Submitting the data set (2/15)

The second component is your final, clean data set, which should be emailed to me by Wednesday, 2/15 with the subject line #math430data. 

Below are some requirements for your submitted data set:

* The data must be in CSV format (.csv).
* Give the file a descriptive name that clearly communicates the context and distinguishes it from the other groups' data files, e.g., group-X.csv, certainly not Data or even Our Statistics Project Data File. Do not use the following words in your file name: project, data, file, statistics, worksheet. Do not use spaces in file names.
* Each observation should be on a separate row of the data file, and each variable should be in a separate column.
* Name all variables helpfully and contextually, e.g., use Airport and WaterTemp, not Individuals and Treatments, and certainly not A and B. Similarly, for the category names, use whole words and phrases, not cryptic codes, e.g., use Male and Female, not 1 and 2, or even M and F. A dichotomous variable Female can be coded 0 for male, and 1 for female (and then is self-documenting). A variable sex coded 1 and 2 is just asking for trouble.
* That said, try to limit your variable and category names to about a dozen characters. This may take some abbreviation.
* Be sure that are sufficient numbers of individuals in each category of each categorical variable! If there are categories with too few individuals for you to spot any trends or to make meaningful inferences, create an additional version of this variable with fewer, consolidated categories (perhaps including an "Other" or "Miscellaneous" category).
* Check for typos! Manual inspection is OK, but its tedious and its easy to overlook misspellings. Running some simple analyses can more quickly make most data entry errors obvious

## Project Presentations (beginning 3/10)


An effective oral presentation is an integral part of this project. One of the objectives of this class is to give you experience conveying the results of a technical investigation to a non-technical audience in a way that they can understand. Whether you choose to stay in academia or pursue a career in industry, the ability to communicate clearly is extremely important. As a data analyst, the burden of proof is on you to convince your audience that what you are saying is true. If your audience (who may very well be less knowledgeable about statistics than you are) cannot understand your results or their interpretations, then the technical merit of your project is irrelevant.

You will make a 15-minute oral presentation to the class. You should make (good) slides. Your goal should be to convey to your audience a clear understanding of your research question, along with a basic understanding of your model, and how well it addresses the research question you posed. You should not tell us everything that you did, or show a bunch of models that didn't work well. After hearing your talk, each student in the class should be able to answer:

- What was your project about?
- What kind of model did you build?
- How well did it work?
- What did you learn from your model(s) about the topic at hand?

You should prepare electronic slides for your talk. HTML5, PowerPoint, Keynote, Google Presentation, Beamer (LaTeX), or alternatively, non-linear presentation software like Prezi are also fine. Be creative! One thing you **should not** do is walk us through your calculations in RStudio. 


### Advice


Advice There are many sources of advice for how to make a good presentation, but an excellent place to start is: http://techspeaking.denison.edu/

Watch the videos on this site to identify some common mistakes. You should also read Joe Gallian's [article](http://www.d.umn.edu/~jgallian/goodPPtalk.pdf) on how to make a good presentation.
Here is some general advice:

- Budget your time. You only have 15 minutes, and we will be running a very tight schedule. If your talk runs too short or too long, it makes you seem unprepared. Rehearse your talk ahead of time (with your group) several times in order to get a better feel for your timing. Talking faster in order to speed up is not a good strategy---you are much better off simply cutting material ahead of time. You will probably have a hard time getting through 15 slides in 15 minutes.
- Don't write too much on each slide. You don't want people to have to read your slides, because if the audience is reading your slides, then they aren't listening to you. You want your slides to provide visual cues to the points that you are making---not substitute for your spoken words. Concentrate on graphical displays and bullet-pointed lists of ideas.
- Put your problem in context. Remember that most of your audience will have little or no knowledge of your subject matter. The easiest way to lose people is to dive right into technical details that require prior ``domain knowledge.'' Spend a few minutes at the beginning of your talk introducing your audience to the most basic aspects of your topic and present some motivation for what you are studying.
- Speak loudly and clearly. Remember that you know more about your topic that anyone else in the room, so speak and act with confidence!
- Tell a story---not necessarily the whole story. It is unrealistic to expect that you can tell your audience everything that you know about your topic in 15 minutes. You should strive to convey the big ideas in a clear fashion, but not dwell on the details. Your talk will be successful if your audience is able to walk away with an understanding of what your research question was, how you addressed it, and what the implications of your findings are.


## Technical Report (3/13)

Your technical report will be a R Markdown file (.Rmd) that contains your R code interspersed with explanations of what the code is doing and what it tells you about the problem. It will be due at 8:00 a.m. on Monday 3/13.

### Content
You do not need to present all of the R code that you wrote throughout the process of working on this project. Rather, the technical report should contain the minimal set of R code that is necessary to understand your results and findings in full. If you make a claim, it must be justified by explicit calculation. A knowledgeable reviewer should be able to compile your .Rmd file without modification, and verify every statement that you have made. All of the R code necessary to produce your figures and tables must appear in the technical report. In short, the technical report should enable a reviewer to reproduce your work.

### Tone
Unlike the presentation, which is aimed at a general audience, this document should be written for reviewers who comprehend statistics at least as well as you do. You should aim for a level of complexity that is more statistically sophisticated than an article in the Science section of *The New York Times*, but less sophisticated than an academic journal. (*Chance* magazine might provide a good example.) For example, you may use terms that that you will likely never see in the *Times* (e.g. residuals), but should not dwell on technical points with no obvious ramifications for the reader (e.g. reporting t-statistics). Your goal for this paper is to convince a statistically-minded reader (e.g. a student in this class, or a student from another school who has taken a statistics class) that you have addressed an interesting research question in a meaningful way. Even a reader with no background in statistics should be able to read your paper and get the gist of it.

### Format

Your technical report should follow this basic format:


- Abstract: a short, one paragraph explanation of your project. The abstract should not consist of more than 5 or 6 sentences, but should relate what you studied and what you found. It need only convey a general sense of what you actually did. The purpose of the abstract is to give a prospective reader enough information to decide if they want to read the full paper.
- Introduction: an overview of your project. In a few paragraphs, you should explain clearly and precisely what your research question is, why it is interesting, and what contribution you have made towards answering that question. You should give an overview of the specifics of your model, but not the full details. Most readers never make it past the introduction, so this is your chance to hook the reader, and is in many ways the most important part of the paper.
- Data: a brief description of your data set. What variables are included? Where did they come from? What are units of measurement? What is the population that was sampled? How was the sample collected? You should also include some basic univariate analysis.
- Results: an explanation of what your model tells us about the research question. You should interpret relevant coefficients in context. What does your model tell us that we did not already know before? You may want to include negative results, but be careful about how you interpret them. For example, you may want to say something along the lines of: "we found no evidence that explanatory variable x is associated with response variable y", or "explanatory variable x did not provide any additional explanatory power above what was already conveyed by explanatory variable z." On other hand, you probably shouldn't claim: "there is no relationship between x and y."
- Conclusion: a summary of your findings and a discussion of their limitations. First, remind the reader of the question that you originally set out to answer, and summarize your findings. Second, discuss the limitations of your model, and what could be done to improve it. You might also want to do the same for your data. This is your last opportunity to clarify the scope of your findings before a journalist misinterprets them and makes wild extrapolations! Protect yourself by being clear about what is not implied by your research.
