---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_float: yes
---

**Instructor:** Adam Loy

**Email:** adam.m.loy@lawrence.edu

**Class Time/Location:** MWF 9:50-11:00 a.m. in Briggs 419

**Office Hours:** MW 3:10--4:30 p.m., T 10:30 a.m.--noon, F 11:00 a.m.--12:30 p.m. in Briggs 410


## Expected Learning Outcomes
After finishing this course, you should have the skills to (i) properly assess if regression is an appropriate data analysis tool for a problem, (ii) correctly utilize regression models to answer complex questions from data, and (iii) clearly present results your from a regression analysis. In terms of more specific skills, by the end of the term you should be able to:

1. Fit a regression model in R and interpret the output.
2. Apply appropriate transformations to the response variable to improve agreement with the model assumptions.
3. Use residual and influence diagnostics to assess model fit and agreement with model assumptions, and to identify outliers and influential observations.
4. Create sets of indicator variables for categorical variables.
5. Apply step-wise model selection to select the most significant explanatory variables from a large data set.
6. Fit a logistic regression model in R and interpret the output.


## Course Logistics

#### Prerequisites:
Math 240 or a comparable course in probability. Previous exposure to statistics and matrix algebra will be useful, but not assumed.

#### Required textbook:
*A Modern Approach to Regression with R*, Simon J. Sheather, 2009, Springer, ISBN 978-0-387-09607-0.

#### Computing:
Modern statistical analysis is done in a computing environment, so this course has a strong computational focus. We will use the R language with the RStudio interface, which are both free and open-source. You have two options for using RStudio:

1. The **server** version of RStudio on the web at (http://rstudio.lawrence.edu/). The advantage
of using the server version is that all of your work will be stored in the cloud, where it is automatically saved and backed up. This means that you can access your work from any computer on campus using a web browser. The downside is that you can't access the server off campus (yes, this includes Bjorklunden) and that you have to share limited computational resources with each other!

2. A **local** version of RStudio installed on your machine. This is recommended due to the computational resources this course demands. The downside to this approach is that your work is only stored locally, but I get around this problem by keeping all of my work in a Dropbox folder. I will also show you how to use GitHub for version control.

Note that you do not have to choose one or the other, you may use both. However, it is important that you understand the distinction so that you can keep track of your work. Both R and RStudio are free and open-source. 


## Course Components

#### Preparation and study: 
You must read the assigned sections of the text before we discuss them in class so that you are already working with the ideas in advance of hearing about them from me. In addition, review your lecture notes after each lecture, carefully reconstructing for yourself the ideas, arguments, and overall story that is developing. Coming to class for 70 minutes 3 times a week is not sufficient to learn statistics and reorganize your thought processes.

#### Class attendance: 
During class we will explore the statistical thought process through lecture, discussion, and hands-on data analysis. Office hours are not substitutes for class attendance.

#### Homework: 
Analyzing data is the only way to deeply learn the thought process behind statistical modeling. Homework for this class will be assigned (most) Wednesdays and due the following week. Homework will solidify important results and give you an opportunity to analyze data. All analyses should be completed in R and summaries should be written using R markdown.


#### Midterm: 
There will be one midterm exam used to gauge your understanding of simple and multiple regression. The date of the exam will be announced in class at least one week prior.


#### Final project:

Much of this course is a build up to the final project, which is a capstone experience synthesizing everything you have learned over the course of the term. This is an opportunity for you to exercise your creativity and create something meaningful. The project will require you to complete the entire statistical modeling process---from formulating questions to reporting your final model---using a data set of your choice. More details about the project will follow.


## Course Policies

#### Evaluation: 
Homework assignments will be worth a total of 50% of your final grade, the midterm will be worth 20%, and the final project will be work 30%.

#### Homework Policies: 
Homework will be due on (most) Wednesdays by 4:30 p.m., allowing you to submit your homework and enjoy some treats at Math Tea!

I will allow you to discuss homework problems with your fellow classmates, but I insist that you write up and submit your own solutions. I am allowing you to discuss problems so that you can share problem solving strategies, not so that you can avoid doing the problems yourself. Remember that copying another student’s work is a violation of the honor code.

You will be graded on the correctness of your solutions and how easy they are to read and understand. You will receive full credit for a solution to a problem if and only if a randomly selected student in the class would understand how to do the problem after having read your solution. No late homework will be accepted, but your lowest grade will be dropped.

#### Classroom Culture: 
If you would rather be talking, sleeping, reading the news, listening to music, or texting, I suggest that you do that somewhere much more comfortable than the classroom. When you attend class, please arrive on time and stay engaged throughout the entire class.

#### Honor Code: 
> *No Lawrence student will unfairly advance their own academic performance or in any way limit or impede the academic pursuits of other students of the Lawrence community.* 

All students are expected to uphold Lawrence University’s Honor Code. All work on exams must be your own. You may collaborate on homework, but you must submit your own assignment that reflects your own thinking, work and organization. Any assignment you submit for a grade should be your own work, and not a facsimile of a classmate’s work, which would constitute academic dishonesty. To check if your homework meets this standard, imagine I asked you to explain your reasoning for each problem---you should be able to do so with ease using language similar to your submission. All written work must be accompanied by a reaffirmation of the Honor Code. Finally, cell phones will be prohibited during exams.

#### Disability Policy: 
Lawrence University is committed to providing reasonable accommodations for students with disabilities. Students establish eligibility and request accommodations through the Center for Academic Success. View the Accessibility Services web page at go.lawrence.edu/cas for more information.

#### Healthy Balance: 
All members of the Lawrence community—students, staff, and faculty—have the responsibility to promote balance in their lives by making thoughtful choices. Balance results from two skills: avoiding imbalance through careful planning, and managing and containing imbalance when it occurs. This course will be demanding, but should not overwhelm your academic (let alone whole) life. If it threatens to, come talk to me, a tutor, friend, counselor, or advisor.